##
##  Makefile -- Build procedure for sample virgule Apache module
##  Autogenerated via ``apxs -n virgule -g'', then heavily edited by RLL.
##

#   the used tools
APXS=/usr/sbin/apxs

APACHECTL=sudo /etc/rc.d/init.d/httpd

#   additional defines, includes and libraries
#DEF=-Dmy_define=my_value


CFLAGS=-Wall -Wmissing-prototypes -I`$(APXS) -q INCLUDEDIR` `$(APXS) -q CFLAGS CFLAGS_SHLIB` `glib-config --cflags` `xml2-config --cflags` `apr-config --cflags` `apr-config --includes` -fPIC
# Original Makefile used LD_SHLIB here but it doesn't work for me
#LD=`$(APXS) -q LD_SHLIB`
LD=ld
LDLIBS=`$(APXS) -q LIBS_SHLIB` `glib-config --libs` `xml2-config --libs` `apr-config --link-ld` `apr-config --libs`
LDFLAGS=`$(APXS) -q LDFLAGS_SHLIB` `apr-config --ldflags` -shared

OBJS = mod_virgule.o buffer.o site.o apache_util.o \
	hashtable.o \
	acct_maint.o util.o auth.o style.o xml_util.o certs.o \
	req.o \
	db.o db_ops.o db_xml.o schema.o \
	net_flow.o tmetric.o \
	diary.o article.o rss_export.o proj.o \
	wiki.o \
	xmlrpc.o xmlrpc-methods.o \
	rating.o eigen.o

#   the default target
all: mod_virgule.so

#   compile the shared object file
mod_virgule.so: $(OBJS)
	$(LD) $(LDFLAGS) -o $@ $^ $(LDLIBS)

#   install the shared object file into Apache 
install: all
	#$(APXS) -i -a -n 'virgule' mod_virgule.so

#   cleanup
clean:
	-rm -f $(OBJS) mod_virgule.so

#   simple test
test: reload
	lynx -mime_header http://localhost/virgule

#   install and activate shared object by reloading Apache to
#   force a reload of the shared object file
reload: install restart

#   the general Apache start/restart/stop
#   procedures
start:
	$(APACHECTL) start
restart:
	$(APACHECTL) restart
stop:
	$(APACHECTL) stop

#   make dep maintains all the dependencies in the Makefile
dep:
	makedepend -Y *.c 2>/dev/null

# DO NOT DELETE
